/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guiEtelas.partidasFolder;

import controller.estadios.DesignacaoController;
import controller.selecoes.SelecaoController;
import domain.classes.estadios.Arbitro;
import domain.classes.partidas.Partida;
import domain.classes.selecoes.Selecao;
import domain.classes.partidas.Fase;
import controller.partidas.PartidaController;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 *
 * @author giova
 */
public class consultarPartida extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(consultarPartida.class.getName());

    private final PartidaController partidaController = new PartidaController();
    private final DesignacaoController designacaoController = new DesignacaoController();
    /* Atributo para guardar qual foi a lista de partidas mostrada na JTable pela última vez,
    para poder fazer as edições e deleções de partidas */
    private List<Partida> partidasMostradas = null;

    /**
     * Creates new form consultarPartida
     */
    public consultarPartida() {
        initComponents();
        carregarFasesESelecoes();

        /* Como ainda não há partidas na tela, os botões começam cinzas */
        mostrarBotoes(false);
    }

    private void mostrarBotoes(boolean mostrar) {
        botaoEditar.setEnabled(mostrar);
        botaoExcluir.setEnabled(mostrar);
    }

    private void carregarFasesESelecoes() {
        for (Fase f : Fase.values()) {
            menuFase.addItem(f);
        }

        // TODO: Pegar seleções pelo Controller

        menuFase.setSelectedIndex(-1);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaPartidas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        menuSelecao = new javax.swing.JComboBox<>();
        menuFase = new javax.swing.JComboBox<>();
        botaoBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        caixaData = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botaoExcluir = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar Partidas - Copa 2026");
        setMaximumSize(new java.awt.Dimension(626, 419));
        setMinimumSize(new java.awt.Dimension(626, 419));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Partidas encontradas"));

        tabelaPartidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Data", "Horário", "Fase", "Estádio", "Sel. 1", "Placar", "Sel. 2", "Status", "Árbitro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaPartidas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 680, 340));

        botaoBuscar.setText("Buscar");
        botaoBuscar.addActionListener(this::botaoBuscarActionPerformed);

        jLabel1.setText("Data: ");

        caixaData.setText("dd/MM/yyyy");

        jLabel2.setText("Filtrar por: ");

        jLabel3.setText("Fase:");

        jLabel4.setText("Seleção:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menuSelecao, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menuFase, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caixaData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoBuscar))
                    .addComponent(jLabel2))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuSelecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuFase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(caixaData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoBuscar)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 670, 60));

        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(this::botaoExcluirActionPerformed);
        getContentPane().add(botaoExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        botaoEditar.setText("Editar");
        botaoEditar.addActionListener(this::botaoEditarActionPerformed);
        getContentPane().add(botaoEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarActionPerformed
        String dataFiltro = caixaData.getText();
        if (dataFiltro.equals("dd/MM/yyyy")) {
            dataFiltro = "";
        }
        partidasMostradas = partidaController.filtrarPartidas(null, (Selecao) menuSelecao.getSelectedItem(),
                (Fase) menuFase.getSelectedItem(), dataFiltro
        );

        mostrarBotoes(!partidasMostradas.isEmpty()); // Mostrar se a lista não estiver vazia, esconder se estiver

        DefaultTableModel modelo = (DefaultTableModel) tabelaPartidas.getModel();
        modelo.setRowCount(0);

        DateTimeFormatter formatoData = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        DateTimeFormatter formatoHora = DateTimeFormatter.ofPattern("HH:mm");

        /* Mostrar as partidas na tabela */
        for (Partida p : partidasMostradas) {
            String data = p.getDataEHora().format(formatoData);
            String hora = p.getDataEHora().format(formatoHora);

            /* Placar só se tiver */
            String placar = "-";
            if (p.getResultado() != null) {
                placar = p.getResultado().getPlacarSelecao1() + " x " + p.getResultado().getPlacarSelecao2();
            }

            Arbitro arbitroPrincipal = designacaoController.buscarArbitroPrincipal(p);

            Object[] linha = {
                    data,
                    hora,
                    p.getFase(),
                    p.getEstadio(),
                    p.getSelecao1(),
                    placar,
                    p.getSelecao2(),
                    p.getStatus(),
                    arbitroPrincipal
            };

            modelo.addRow(linha);
        }

    }//GEN-LAST:event_botaoBuscarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        /* A princípio, esse botão só foi clicado se tem pelo menos uma partida na tabela */
        int index = tabelaPartidas.getSelectedRow();

        if (index == -1) {
            JOptionPane.showMessageDialog(this,
                    "Selecione uma partida da tabela.",
                    "Erro na seleção de partida",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        Partida partida = partidasMostradas.get(index);

        int confirmar = JOptionPane.showConfirmDialog(
                this,
                "Tem certeza que você quer excluir essa partida?",
                "Confirmar exclusão",
                JOptionPane.YES_NO_OPTION
        );

        if (confirmar == JOptionPane.YES_OPTION) {
            partidaController.excluirPartida(partida);

            DefaultTableModel modelo = (DefaultTableModel) tabelaPartidas.getModel();
            modelo.removeRow(index);
            partidasMostradas.remove(index);

            JOptionPane.showMessageDialog(this, "Partida excluída com sucesso.");
        }

    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
        /* Usar a mesma tela de cadastro, mas já preenchendo todos os campos automaticamente */
        /* Da mesma forma, para chegar aqui precisa ter pelo menos uma partida na tabela */
        int index = tabelaPartidas.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this,
                    "Selecione uma partida da tabela.",
                    "Erro na seleção de partida",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        Partida partida = partidasMostradas.get(index);

        cadastrarNovaPartida telaEdicao = new cadastrarNovaPartida(partida);
        telaEdicao.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new consultarPartida().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JTextField caixaData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<Fase> menuFase;
    private javax.swing.JComboBox<Selecao> menuSelecao;
    private javax.swing.JTable tabelaPartidas;
    // End of variables declaration//GEN-END:variables
}
