/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guiEtelas.arbitrosFolder;

import controller.estadios.ArbitroController;
import domain.classes.administracao.Administrador;
import domain.classes.administracao.SessaoUsuario;
import domain.classes.administracao.Usuario;
import domain.classes.estadios.Arbitro;
import domain.dao.ArbitroDAO;
import domain.dao.ArbitroJsonDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author giova
 */
public class cadastroDeArbitros extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(cadastroDeArbitros.class.getName());

    private ArbitroController arbitroController = new ArbitroController();

    /**
     * Creates new form cadastroDeArbitros
     */
    public cadastroDeArbitros() {
        initComponents();
        
        arbitroController = new ArbitroController();
        
        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtExpArbitro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcbPaisesDisponiveis = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtNomeArbitro = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        btnPesquisarArbitro = new javax.swing.JButton();
        btnDesignarPartida = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableArbitros = new javax.swing.JTable();
        btnEditarArbitro = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciador de Árbitros");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Árbitro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel1.setText("Nome: ");

        jLabel2.setText("Nacionalidade: ");

        jLabel3.setText("Experiência: ");

        jLabel4.setText("Anos");

        jcbPaisesDisponiveis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um País", "África do Sul", "Albânia", "Alemanha", "Angola", "Arábia Saudita", "Argélia", "Argentina", "Austrália", "Áustria", "Bélgica", "Bósnia e Herzegovina", "Brasil", "Cabo Verde", "Camarões", "Canadá", "Catar", "Chile", "China", "Colômbia", "Coreia do Sul", "Costa do Marfim", "Costa Rica", "Croácia", "Curaçao", "El Salvador", "Emirados Árabes Unidos", "Equador", "Escócia", "Eslovênia", "Espanha", "Estados Unidos", "França", "Gabão", "Gana", "Grécia", "Guatemala", "Haiti", "Honduras", "Inglaterra", "Irã", "Iraque", "Itália", "Jamaica", "Japão", "Jordânia", "Kuwait", "Marrocos", "Mauritânia", "México", "Nicarágua", "Noruega", "Nova Zelândia", "Omã", "Países Baixos", "Panamá", "Paraguai", "Peru", "Polônia", "Portugal", "República Checa", "República Democrática do Congo", "Romênia", "Senegal", "Sérvia", "Singapura", "Somália", "Sudão", "Suécia", "Suíça", "Tailândia", "Trinidad e Tobago", "Tunísia", "Turquia", "Uruguai", "Uzbequistão", "Venezuela" }));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("\"Nome\" apenas para fins de busca. Para selecionar árbitros, clique na tabela");

        txtNomeArbitro.addActionListener(this::txtNomeArbitroActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtExpArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbPaisesDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(286, 286, 286))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeArbitro)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbPaisesDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtExpArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(this::btnLimparActionPerformed);

        btnPesquisarArbitro.setText("Pesquisar");
        btnPesquisarArbitro.addActionListener(this::btnPesquisarArbitroActionPerformed);

        btnDesignarPartida.setText("Designar para nova Partida");
        btnDesignarPartida.addActionListener(this::btnDesignarPartidaActionPerformed);

        jTableArbitros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "E-mail", "Nacionalidade", "Experiência"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableArbitros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableArbitrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableArbitros);

        btnEditarArbitro.setText("Editar");
        btnEditarArbitro.addActionListener(this::btnEditarArbitroActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnLimpar)
                        .addGap(76, 76, 76)
                        .addComponent(btnEditarArbitro)
                        .addGap(70, 70, 70)
                        .addComponent(btnPesquisarArbitro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDesignarPartida)
                        .addGap(19, 19, 19)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar)
                    .addComponent(btnPesquisarArbitro)
                    .addComponent(btnDesignarPartida)
                    .addComponent(btnEditarArbitro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void carregarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) jTableArbitros.getModel();
        modelo.setRowCount(0);

        for (Arbitro arbitro : arbitroController.listar()) {
            modelo.addRow(new Object[]{
                arbitro.getCodigo(),
                arbitro.getNomeCompleto(),
                arbitro.getEmail(),
                arbitro.getPais() == null ? "Não atribuído" : arbitro.getPais(),
                arbitro.getExperiencia()
            });
        }
    }
    
    private void limparCampos() {
        txtNomeArbitro.setText("");
        txtExpArbitro.setText("");
        jcbPaisesDisponiveis.setSelectedIndex(0);
        
        txtNomeArbitro.setEditable(true);
    }
    
    
    
    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
        carregarTabela();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnPesquisarArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarArbitroActionPerformed
        try {
            String nome = txtNomeArbitro.getText().trim();
            String pais = (String) jcbPaisesDisponiveis.getSelectedItem();
            
            if ("Todos".equals(pais)) {
                pais = null;
            }

            Integer expMinima = null;
            if (!txtExpArbitro.getText().trim().isEmpty()) {
                expMinima = Integer.parseInt(txtExpArbitro.getText().trim());
            }

            List<Arbitro> resultados = arbitroController.pesquisar(nome, pais, expMinima);

            DefaultTableModel modelo = (DefaultTableModel) jTableArbitros.getModel();
            modelo.setRowCount(0);

            for (Arbitro a : resultados) {
                modelo.addRow(new Object[]{
                    a.getCodigo(),
                    a.getNomeCompleto(),
                    a.getEmail(),
                    a.getPais() == null ? "Não atribuído" : a.getPais(),
                    a.getExperiencia()
                });
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "A experiência inserida para pesquisa deve ser um número inteiro.", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPesquisarArbitroActionPerformed

    private void btnDesignarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesignarPartidaActionPerformed
        int linha = jTableArbitros.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um árbitro na tabela para designar à partida.");
            return;
        }
        
        // Exemplo de como você capturaria o objeto selecionado se precisasse passar para a outra tela:
        String codigo = jTableArbitros.getValueAt(linha, 0).toString();
        Arbitro selecionado = arbitroController.buscarPorCodigo(codigo);
        
        new designarArbitroParaNovaPartida(selecionado).setVisible(true);
    }//GEN-LAST:event_btnDesignarPartidaActionPerformed

    private void btnEditarArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarArbitroActionPerformed
        int linha = jTableArbitros.getSelectedRow();
        
        if (jTableArbitros.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um árbitro na tabela para editar.");
            return;
        }

        try {
            String codigo = jTableArbitros.getValueAt(linha, 0).toString();
            String pais = (String) jcbPaisesDisponiveis.getSelectedItem();
            
            if ("Todos".equals(pais)) {
                JOptionPane.showMessageDialog(this, "Selecione um país válido para o árbitro.");
                return;
            }

            int experiencia = Integer.parseInt(txtExpArbitro.getText().trim());

            // Executa a alteração através do Controller
            arbitroController.editar(codigo, pais, experiencia);

            carregarTabela();
            limparCampos();

            JOptionPane.showMessageDialog(this, "Dados do árbitro atualizados com sucesso!");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, insira um valor numérico válido para a experiência.", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarArbitroActionPerformed

    private void txtNomeArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeArbitroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeArbitroActionPerformed

    private void jTableArbitrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableArbitrosMouseClicked
        int linha = jTableArbitros.getSelectedRow();
        
        if (linha != -1) {
            txtNomeArbitro.setText(jTableArbitros.getValueAt(linha, 1).toString());
            
            // Bloqueia a edição do nome caso esteja usando para atualizar dados cadastrados por Admin
            txtNomeArbitro.setEditable(false); 
            
            String pais = jTableArbitros.getValueAt(linha, 3).toString();
            if (pais.equals("Não atribuído")) {
                jcbPaisesDisponiveis.setSelectedIndex(0);
            } else {
                jcbPaisesDisponiveis.setSelectedItem(pais);
            }
            
            txtExpArbitro.setText(jTableArbitros.getValueAt(linha, 4).toString());
        }
    }//GEN-LAST:event_jTableArbitrosMouseClicked
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // 1. Setup the FlatLaf Light Look and Feel
            try {
            com.formdev.flatlaf.FlatLightLaf.setup();
            } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
            }
            
        //Para testar simulação, des-comente o código abaixo e apague os jsons de arbitro (se houver)
        /*
        Administrador adminTeste = new Administrador(
                "Administrador Teste",
                "admin@teste.com",
                "123",
                Usuario.Tipo.ADMINISTRADOR
        );
        SessaoUsuario.getInstancia().setUsuarioAtual(adminTeste);

        // 3. Utilizando o Controller apropriado para o Mock
        try {
            ArbitroController arbitroController = new ArbitroController();
            
            // Instancia o controller responsável pelas inclusões
            // (Ajuste o nome exato da classe se ela se chamar de outra forma no seu projeto)
            controller.administracao.AdministradorController adminController = new controller.administracao.AdministradorController();

            // Só insere se a base de dados de árbitros estiver zerada
            if (arbitroController.listar().isEmpty()) {
                
                // Chame o método de cadastro do Admin Controller passando o que o método dele espera.
                // Geralmente os dados base que um Admin cria: Nome e E-mail.
                adminController.criaUsuario("Pierluigi Collina", "collina@fifa.com", "SenhaLegal123!", Usuario.Tipo.ARBITRO);
                adminController.criaUsuario("Howard Webb", "webb@premierleague.com", "SenhaLegal123!", Usuario.Tipo.ARBITRO);
                adminController.criaUsuario("Sandro Meira Ricci", "ricci@cbf.com", "SenhaLegal123!", Usuario.Tipo.ARBITRO);
                adminController.criaUsuario("Nestor Pitana", "pitana@afa.com", "SenhaLegal123!", Usuario.Tipo.ARBITRO);

                System.out.println("Árbitros cadastrados via Controller com sucesso para os testes!");
            }
        } catch (Exception e) {
            System.err.println("Não foi possível popular os árbitros via Controller: " + e.getMessage());
        }
        */
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new cadastroDeArbitros().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesignarPartida;
    private javax.swing.JButton btnEditarArbitro;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisarArbitro;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableArbitros;
    private javax.swing.JComboBox<String> jcbPaisesDisponiveis;
    private javax.swing.JTextField txtExpArbitro;
    private javax.swing.JTextField txtNomeArbitro;
    // End of variables declaration//GEN-END:variables
}
