/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guiEtelas.arbitrosFolder;

import controller.estadios.DesignacaoController;
import controller.exceptions.Copa2026Exceptions;
import controller.partidas.PartidaController;
import domain.classes.estadios.Arbitro;
import domain.classes.partidas.Partida;

import javax.swing.*;

/**
 *
 * @author giova
 */
public class designarArbitroParaNovaPartida extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(designarArbitroParaNovaPartida.class.getName());
    private Arbitro arbitro = null;
    DesignacaoController designacaoController = new DesignacaoController();
    PartidaController partidaController = new PartidaController();

    /* Construtor padrão caso precise */
    public designarArbitroParaNovaPartida() {
        initComponents();
    }

    /* Construtor que recebe o árbitro pra preencher o código dele automaticamente */
    public designarArbitroParaNovaPartida(Arbitro arbitro) {
        initComponents();
        preencherCodigoArbitro(arbitro);
        this.arbitro = arbitro;
    }

    private void preencherCodigoArbitro(Arbitro arbitro) {
        String codigo = arbitro.getCodigo();
        caixaCodigoArbitro.setText(codigo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        caixaCodigoArbitro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        caixaCodigoPartida = new javax.swing.JTextField();
        botaoDesignar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Designar árbitro à nova partida");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Designação de Árbitro para Partida", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel1.setText("Código do Árbitro:");

        caixaCodigoArbitro.setText("*inserido automaticamente");

        jLabel2.setText("Código da Partida: ");

        botaoDesignar.setText("Designar");
        botaoDesignar.addActionListener(this::botaoDesignarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caixaCodigoArbitro, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(caixaCodigoPartida))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(botaoDesignar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(caixaCodigoArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(caixaCodigoPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(botaoDesignar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoDesignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDesignarActionPerformed
        Partida partida = null;

        /* Achar a partida pelo código / ID */
        for (Partida p : partidaController.listar()) {
            if (p.getId().equals(caixaCodigoPartida.getText())) {
                partida = p;
            }
        }

        /* Não encontrou partida com esse código / ID */
        if (partida == null) {
            JOptionPane.showMessageDialog(this,
                    "Não foi encontrada uma partida com esse código.",
                    "Erro na busca por partida",
                    JOptionPane.ERROR_MESSAGE
            );
        } else {
            /* Tratamento de exceções */
            try {
                /* Essa só vai ser a principal se a partida ainda não tiver um principal */
                boolean principal = !designacaoController.possuiArbitroPrincipal(partida);
                designacaoController.designar(arbitro, partida, principal);
                JOptionPane.showMessageDialog(this, "Árbitro designado com sucesso!");
                this.dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        e.getMessage(),
                        "Erro na designação",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }

    }//GEN-LAST:event_botaoDesignarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         // 1. Setup the FlatLaf Light Look and Feel
            try {
            com.formdev.flatlaf.FlatLightLaf.setup();
            } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
            }
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new designarArbitroParaNovaPartida().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoDesignar;
    private javax.swing.JTextField caixaCodigoArbitro;
    private javax.swing.JTextField caixaCodigoPartida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
