/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guiEtelas.gestaoDeUsuario;
import controller.administracao.AdministradorController;
import controller.exceptions.Copa2026Exceptions;
import domain.classes.administracao.Usuario;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author JOÃO
 */
public class gestaoDeUsuariosTela extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(gestaoDeUsuariosTela.class.getName());
    private AdministradorController adminController;
    private DefaultTableModel modeloTabela;
    private Usuario usuarioSelecionado;
    private List<Usuario> usuariosAtuais;
    /**
     * Creates new form gestaoDeUsuariosTela
     */
    public gestaoDeUsuariosTela() {
        initComponents();
        adminController = new AdministradorController();
        configurarTabela();
        carregarUsuarios("");

        dialogConfirmarExclusao.setSize(400, 250);
        dialogConfirmarExclusao.setLocationRelativeTo(this);
        dialogConfirmarExclusao.setModal(true);

    }
    
    private void configurarTabela(){
        modeloTabela = new DefaultTableModel() {
        @Override
            public boolean isCellEditable(int row, int column) {
            return false;
            }
        };

        modeloTabela.addColumn("Nome completo");
        modeloTabela.addColumn("Email");
        modeloTabela.addColumn("Cargo");

        tabelaUsuarios.setModel(modeloTabela);
        tabelaUsuarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        tabelaUsuarios.getSelectionModel().addListSelectionListener(e ->{
            if(!e.getValueIsAdjusting()){
                int linha = tabelaUsuarios.getSelectedRow();
                
                if(linha >= 0 && linha < usuariosAtuais.size()){
                    usuarioSelecionado = usuariosAtuais.get(linha);
                }else{
                    usuarioSelecionado = null;
                }
            }
        });
    }
    
    private void carregarUsuarios(String filtro){
        try{

            adminController.recarregarUsuarios();
            modeloTabela.setRowCount(0);
            
            if(filtro == null || filtro.trim().isEmpty()){
                usuariosAtuais = adminController.listarTodosUsuarios();
            }else{
                usuariosAtuais = adminController.buscarUsuariosPorNome(filtro);
            }

            if(usuariosAtuais == null){
                System.err.println("⚠️ usuariosAtuais é NULL!");
                usuariosAtuais = new ArrayList<>();
            }

            for(Usuario u: usuariosAtuais){
                modeloTabela.addRow(new Object[]{
                    u.getNomeCompleto(),
                    u.getEmail(),
                    u.getPersonagem().toString()
                });
            }
        }catch (Copa2026Exceptions e){
            JOptionPane.showMessageDialog(this,e.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void confirmarExclusao(){
        try{
            adminController.excluiUsuario(
                    usuarioSelecionado.getNomeCompleto(),
                    usuarioSelecionado.getEmail()
            );
            
            JOptionPane.showMessageDialog(this,"Usuário excluído!");

            txtBusca.setText("");
            carregarUsuarios("");
            usuarioSelecionado = null;
            dialogConfirmarExclusao.setVisible(false);
        }catch(Copa2026Exceptions e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }
    private void cancelarExclusao(){
        dialogConfirmarExclusao.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogConfirmarExclusao = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        btnCancelarExclusao = new javax.swing.JButton();
        btnConfirmarExclusao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblNomeCompleto = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        btnCriar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        scrollTabela = new javax.swing.JScrollPane();
        tabelaUsuarios = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        txtBusca = new javax.swing.JTextField();

        dialogConfirmarExclusao.setTitle("Confirmação de Exclusão");

        btnCancelarExclusao.setText("Cancelar");
        btnCancelarExclusao.addActionListener(this::btnCancelarExclusaoActionPerformed);

        btnConfirmarExclusao.setText("Confirmar");
        btnConfirmarExclusao.addActionListener(this::btnConfirmarExclusaoActionPerformed);

        jLabel1.setText("Tem certeza que deseja excluir o usuário?");

        lblNomeCompleto.setText("Nome:");

        lblEmail.setText("Email:");

        lblTipo.setText("Cargo:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomeCompleto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTipo)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnCancelarExclusao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfirmarExclusao)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarExclusao)
                    .addComponent(btnConfirmarExclusao))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout dialogConfirmarExclusaoLayout = new javax.swing.GroupLayout(dialogConfirmarExclusao.getContentPane());
        dialogConfirmarExclusao.getContentPane().setLayout(dialogConfirmarExclusaoLayout);
        dialogConfirmarExclusaoLayout.setHorizontalGroup(
            dialogConfirmarExclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogConfirmarExclusaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        dialogConfirmarExclusaoLayout.setVerticalGroup(
            dialogConfirmarExclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogConfirmarExclusaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestão de Usuários");

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btnEditar.setText("Editar usuário");
        btnEditar.setMaximumSize(new java.awt.Dimension(127, 23));
        btnEditar.setMinimumSize(new java.awt.Dimension(127, 23));
        btnEditar.setPreferredSize(new java.awt.Dimension(127, 23));
        btnEditar.addActionListener(this::btnEditarActionPerformed);
        jPanel1.add(btnEditar);

        btnCriar.setText("Criar novo usuário");
        btnCriar.addActionListener(this::btnCriarActionPerformed);
        jPanel1.add(btnCriar);

        btnExcluir.setText("Excluir usuário");
        btnExcluir.setMaximumSize(new java.awt.Dimension(127, 23));
        btnExcluir.setMinimumSize(new java.awt.Dimension(127, 23));
        btnExcluir.setPreferredSize(new java.awt.Dimension(127, 23));
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);
        jPanel1.add(btnExcluir);

        tabelaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome completo", "Email", "Cargo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollTabela.setViewportView(tabelaUsuarios);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);
        jPanel2.add(btnBuscar);

        txtBusca.setText("Nome Completo");
        txtBusca.addActionListener(this::txtBuscaActionPerformed);
        jPanel2.add(txtBusca);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(scrollTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(scrollTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        if(usuarioSelecionado == null){
            JOptionPane.showMessageDialog(this,"Selecione um Usuário!");
            return;
        }
        
        lblNomeCompleto.setText("Nome: " + usuarioSelecionado.getNomeCompleto());
        lblEmail.setText("Email: " + usuarioSelecionado.getEmail());
        lblTipo.setText("Tipo: " + usuarioSelecionado.getPersonagem().toString());

        dialogConfirmarExclusao.setVisible(true);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        carregarUsuarios(txtBusca.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        if(usuarioSelecionado == null){
            JOptionPane.showMessageDialog(this,"Selecione um usuário!");
            return;
        }
        editarUsuarioTela tela = new editarUsuarioTela(usuarioSelecionado);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                // Quando a tela fechar, recarrega
                adminController.recarregarUsuarios();
                txtBusca.setText("");
                carregarUsuarios("");
            }
        });
        tela.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarExclusaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarExclusaoActionPerformed
        // TODO add your handling code here:
        cancelarExclusao();
    }//GEN-LAST:event_btnCancelarExclusaoActionPerformed

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        // TODO add your handling code here:
        criaUsuarioTela tela =  new criaUsuarioTela();
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                // Quando a tela fechar, recarrega
                adminController.recarregarUsuarios();
                txtBusca.setText("");
                carregarUsuarios("");
            }
        });
        tela.setVisible(true);
    }//GEN-LAST:event_btnCriarActionPerformed

    private void btnConfirmarExclusaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarExclusaoActionPerformed
        // TODO add your handling code here:
        confirmarExclusao();
    }//GEN-LAST:event_btnConfirmarExclusaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new gestaoDeUsuariosTela().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelarExclusao;
    private javax.swing.JButton btnConfirmarExclusao;
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JDialog dialogConfirmarExclusao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNomeCompleto;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JScrollPane scrollTabela;
    private javax.swing.JTable tabelaUsuarios;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
