/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guiEtelas.loginEsignupFolder;

import controller.exceptions.Copa2026Exceptions;
import domain.classes.administracao.Usuario;
import domain.classes.estadios.Arbitro;
import domain.dao.UsuarioDAO;
import domain.dao.UsuarioJsonDAO;
import domain.dao.ArbitroDAO;
import domain.dao.ArbitroJsonDAO;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.ArrayList;

/**
 *
 * @author JOÃO
 */
public class TelaEsqueciSenha extends javax.swing.JFrame {
     
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaEsqueciSenha.class.getName());
        private UsuarioJsonDAO usuarioDAO;
        private ArbitroJsonDAO arbitroDAO;
        private Usuario usuarioEncontrado;
        private List<Usuario> todosUsuarios;
    /**
     * Creates new form NewJFrame
     */
    public TelaEsqueciSenha() {
        initComponents();
        usuarioDAO = new UsuarioJsonDAO();
        arbitroDAO = new ArbitroJsonDAO();
        
        carregarTodosUsuarios();
        
        jSeparator2.setVisible(false);
        lblUsuario.setVisible(false);
        lblNovaSenha.setVisible(false);
        txtNovaSenha.setVisible(false);
        lblConfirmarSenha.setVisible(false);
        txtConfirmarSenha.setVisible(false);
        btnRedefinir.setVisible(false);
        btnVoltar.setVisible(false);
        
        setLocationRelativeTo(null);
        
        carregarTodosUsuarios();
        
        txtEmail.addActionListener(e -> btnBuscarActionPerformed(null));
        getRootPane().setDefaultButton(btnBuscar);
    }

    private void carregarTodosUsuarios(){
        todosUsuarios = usuarioDAO.carregar();
    }
    
    private void atualizarSenha(Usuario usuario, String novaSenha)throws Copa2026Exceptions{
        List<Usuario> usuarios = usuarioDAO.carregar();
        boolean encontrado = false;
        
        for(Usuario u: usuarios){
            if(u.getEmail().equals(usuario.getEmail())){
                u.setSenha(novaSenha);
                encontrado = true;
                break;
            }
        }
        if(!encontrado){
            throw new Copa2026Exceptions("Usuário não encontrado!");
        }
        usuarioDAO.salvar(usuarios);
        
        if(usuario.getPersonagem() == Usuario.Tipo.ARBITRO){
            List<Arbitro> arbitros = arbitroDAO.carregar();
            boolean encontradoArbitro = false;
            
            for(Arbitro a: arbitros){
                if(a.getEmail().equals(usuario.getEmail())){
                    a.setSenha(novaSenha);
                    encontradoArbitro = true;
                    break;
                }
            }
            if(!encontradoArbitro){
                Arbitro novoArbitro = new Arbitro(usuario.getNomeCompleto(),
                        usuario.getEmail(),novaSenha,Usuario.Tipo.ARBITRO
                );
                arbitros.add(novoArbitro);
            }
            arbitroDAO.salvar(arbitros);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblNovaSenha = new javax.swing.JLabel();
        txtNovaSenha = new javax.swing.JPasswordField();
        lblConfirmarSenha = new javax.swing.JLabel();
        txtConfirmarSenha = new javax.swing.JPasswordField();
        btnVoltar = new javax.swing.JButton();
        btnRedefinir = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Redefinir Senha - Copa 2026");

        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblTitulo.setText("RECUPERAR SENHA!");
        lblTitulo.setPreferredSize(new java.awt.Dimension(109, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 6, 0, 0);
        jPanel1.add(lblTitulo, gridBagConstraints);

        lblUsuario.setText("Usuário encontrado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 6, 0, 0);
        jPanel1.add(lblUsuario, gridBagConstraints);

        jLabel2.setText("Digite seu e-mail cadastrado:");
        jLabel2.setPreferredSize(new java.awt.Dimension(156, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        txtEmail.addActionListener(this::txtEmailActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.ipadx = 233;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel1.add(txtEmail, gridBagConstraints);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 67, 0, 0);
        jPanel1.add(btnBuscar, gridBagConstraints);

        lblNovaSenha.setText("Nova senha:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 6, 0, 0);
        jPanel1.add(lblNovaSenha, gridBagConstraints);

        txtNovaSenha.addActionListener(this::txtNovaSenhaActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.ipadx = 234;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel1.add(txtNovaSenha, gridBagConstraints);

        lblConfirmarSenha.setText("Confirmar senha:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        jPanel1.add(lblConfirmarSenha, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.ipadx = 234;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel1.add(txtConfirmarSenha, gridBagConstraints);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 10, 6, 0);
        jPanel1.add(btnVoltar, gridBagConstraints);

        btnRedefinir.setText("Redefinir");
        btnRedefinir.addActionListener(this::btnRedefinirActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 32;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 178, 6, 0);
        jPanel1.add(btnRedefinir, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 34;
        gridBagConstraints.ipadx = 657;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 0, 0, 0);
        jPanel1.add(jSeparator2, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNovaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNovaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNovaSenhaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String email = txtEmail.getText().trim();
        
        if(email.isEmpty()){
            JOptionPane.showMessageDialog(this,"Digite seu e-mail para recuperar a senha!","Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        usuarioEncontrado = null;
        for(Usuario u: todosUsuarios){
            if(u.getEmail().equalsIgnoreCase(email)){
                usuarioEncontrado = u;
                break;
            }
        }
        if(usuarioEncontrado == null){
            JOptionPane.showMessageDialog(this,"E-mail não encontrado!\nVerifique se escreveu corretamente","Usuário não encontrado",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        jSeparator2.setVisible(true);
        lblUsuario.setText("Usuário encontrado: " + usuarioEncontrado.getNomeCompleto());
        lblUsuario.setVisible(true);
        lblNovaSenha.setVisible(true);
        txtNovaSenha.setVisible(true);
        lblConfirmarSenha.setVisible(true);
        txtConfirmarSenha.setVisible(true);
        btnRedefinir.setVisible(true);
        btnVoltar.setVisible(true);
        
        pack();
        setLocationRelativeTo(null);
        
        txtNovaSenha.requestFocus();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRedefinirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedefinirActionPerformed
        // TODO add your handling code here:
        String novaSenha = new String(txtNovaSenha.getPassword());
        String confirmarSenha = new String(txtConfirmarSenha.getPassword());
        
        if(novaSenha.isEmpty() || confirmarSenha.isEmpty()){
            JOptionPane.showMessageDialog(this,"Preencha todos os campos!","Aviso",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!novaSenha.equals(confirmarSenha)){
            JOptionPane.showMessageDialog(this,"As senhas não conferem!","Aviso",JOptionPane.WARNING_MESSAGE);
            txtNovaSenha.setText("");
            txtConfirmarSenha.setText("");
            txtNovaSenha.requestFocus();
            return;
        }
        if(novaSenha.length() < 8){
            JOptionPane.showMessageDialog(this,"Nova senha deve conter no mínimo 8 caracteres","Erro",JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            atualizarSenha(usuarioEncontrado,novaSenha);
            JOptionPane.showMessageDialog(this,"Senha redefinida com sucesso","Aviso", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Erro ao redefinir senha","Erro",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRedefinirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaEsqueciSenha().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRedefinir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblConfirmarSenha;
    private javax.swing.JLabel lblNovaSenha;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtConfirmarSenha;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtNovaSenha;
    // End of variables declaration//GEN-END:variables
}
