/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guiEtelas.estadiosFolder;

import controller.estadios.EstadioController;
import domain.classes.administracao.Administrador;
import domain.classes.administracao.SessaoUsuario;
import domain.classes.administracao.Usuario;
import domain.classes.estadios.Estadio;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author giova
 */
public class TelaInicialEstadios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaInicialEstadios.class.getName());

    /**
     * Creates new form TelaInicialEstadios
     */
    
    private final EstadioController estadioController;
    
    public TelaInicialEstadios() {
        initComponents();
        
        estadioController = new EstadioController();

        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jpnlDadosEstadio = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcbSelecionarPais = new javax.swing.JComboBox<>();
        estadoPartida = new javax.swing.JTextField();
        cidadePartida = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nomeEstadio = new javax.swing.JTextField();
        idEstadio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtLotacaoMax = new javax.swing.JTextField();
        txtAnoInauguracao = new javax.swing.JTextField();
        botaoNovo = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        botaoPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEstadios = new javax.swing.JTable();

        jTextField2.setText("jTextField2");

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciamento de Estádios");
        setResizable(false);

        jpnlDadosEstadio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Estádio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Tai Le", 1, 12))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Localização", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel2.setText("País:");

        jLabel3.setText("Estado: ");

        jLabel4.setText("Cidade: ");

        jcbSelecionarPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Canadá", "Estados Unidos", "México" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cidadePartida))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbSelecionarPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estadoPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbSelecionarPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(estadoPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cidadePartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel5.setText("Nome: ");

        jLabel6.setText("Código ID: ");

        jLabel1.setText("Ano de Inauguração: ");

        jLabel7.setText("Lotação máxima:");

        txtLotacaoMax.setToolTipText("1000");

        txtAnoInauguracao.setToolTipText("yyyy");
        txtAnoInauguracao.addActionListener(this::txtAnoInauguracaoActionPerformed);

        javax.swing.GroupLayout jpnlDadosEstadioLayout = new javax.swing.GroupLayout(jpnlDadosEstadio);
        jpnlDadosEstadio.setLayout(jpnlDadosEstadioLayout);
        jpnlDadosEstadioLayout.setHorizontalGroup(
            jpnlDadosEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlDadosEstadioLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jpnlDadosEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlDadosEstadioLayout.createSequentialGroup()
                        .addGroup(jpnlDadosEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpnlDadosEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnlDadosEstadioLayout.createSequentialGroup()
                        .addGroup(jpnlDadosEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnlDadosEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLotacaoMax, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAnoInauguracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpnlDadosEstadioLayout.setVerticalGroup(
            jpnlDadosEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlDadosEstadioLayout.createSequentialGroup()
                .addGroup(jpnlDadosEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnlDadosEstadioLayout.createSequentialGroup()
                        .addGroup(jpnlDadosEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(nomeEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpnlDadosEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(15, 15, 15)
                        .addGroup(jpnlDadosEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtAnoInauguracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpnlDadosEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLotacaoMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(3, 3, 3))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        botaoNovo.setText("Novo");
        botaoNovo.addActionListener(this::botaoNovoActionPerformed);

        botaoEditar.setText("Editar");
        botaoEditar.addActionListener(this::botaoEditarActionPerformed);

        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(this::botaoExcluirActionPerformed);

        botaoPesquisar.setText("Pesquisar");
        botaoPesquisar.addActionListener(this::botaoPesquisarActionPerformed);

        jTableEstadios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Código", "Lotação", "Ano", "País", "Estado", "Cidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableEstadios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEstadiosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEstadios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpnlDadosEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(botaoNovo)
                                .addGap(109, 109, 109)
                                .addComponent(botaoEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoExcluir)
                                .addGap(117, 117, 117)
                                .addComponent(botaoPesquisar)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnlDadosEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoNovo)
                    .addComponent(botaoEditar)
                    .addComponent(botaoExcluir)
                    .addComponent(botaoPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void carregarTabela(){

        DefaultTableModel modelo =
                (DefaultTableModel) jTableEstadios.getModel();

        modelo.setRowCount(0);

        for(Estadio estadio :
                estadioController.listar()){

            modelo.addRow(new Object[]{
                    estadio.getNome(),
                    estadio.getCodigo(),
                    estadio.getCapacidade(),
                    estadio.getAnoInauguracao(),
                    estadio.getPais(),
                    estadio.getEstado(),
                    estadio.getCidade()
            });
        }
    }
    
    private void limparCampos(){

    idEstadio.setText("");
    nomeEstadio.setText("");

    txtAnoInauguracao.setText("");
    txtLotacaoMax.setText("");

    estadoPartida.setText("");
    cidadePartida.setText("");

    jcbSelecionarPais.setSelectedIndex(0);
    
    idEstadio.setEditable(true);
    }
    
    private void botaoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoActionPerformed
        System.out.println("Botão Clicado");
        
        try {

        String codigo = idEstadio.getText().trim();
        String nome = nomeEstadio.getText().trim();

        int ano = Integer.parseInt(
                txtAnoInauguracao.getText().trim()
        );

        int capacidade = Integer.parseInt(
                txtLotacaoMax.getText().trim()
        );

        String pais =
                (String) jcbSelecionarPais.getSelectedItem();
        
        if ("Todos".equals(pais)) {
            JOptionPane.showMessageDialog(
                    this,
                    "Selecione um país válido."
            );
            return;
        }

        String estado =
                estadoPartida.getText().trim();

        String cidade =
                cidadePartida.getText().trim();

        Estadio estadio =
                new Estadio(
                        codigo,
                        nome,
                        ano,
                        capacidade,
                        pais,
                        estado,
                        cidade
                );

        estadioController.cadastrar(estadio);

        carregarTabela();

        limparCampos();

        JOptionPane.showMessageDialog(
                this,
                "Estádio cadastrado com sucesso!"
        );

        } catch(Exception e){

            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage()
            );
        }
    }//GEN-LAST:event_botaoNovoActionPerformed

    
    private void botaoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarActionPerformed
        System.out.println("Botão Clicado");
        
        try {
        String pais = jcbSelecionarPais.getSelectedItem().equals("Todos") ? null : (String) jcbSelecionarPais.getSelectedItem();
        List<Estadio> resultados =
                estadioController.pesquisar(
                        nomeEstadio.getText().trim(),
                        pais,
                        estadoPartida.getText().trim(),
                        cidadePartida.getText().trim(),
                        txtLotacaoMax.getText().isBlank()
                                ? null
                                : Integer.parseInt(txtLotacaoMax.getText())
                );

        DefaultTableModel modelo =
                (DefaultTableModel) jTableEstadios.getModel();

        modelo.setRowCount(0);

        for (Estadio estadio : resultados) {

            modelo.addRow(new Object[]{
                    estadio.getNome(),
                    estadio.getCodigo(),
                    estadio.getCapacidade(),
                    estadio.getAnoInauguracao(),
                    estadio.getPais(),
                    estadio.getEstado(),
                    estadio.getCidade()
            });
        }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage()
            );
        }
    }//GEN-LAST:event_botaoPesquisarActionPerformed
    
    
    
    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        System.out.println("Botão Clicado");
        
        int linha = jTableEstadios.getSelectedRow();

        if(linha == -1){
            JOptionPane.showMessageDialog(
                    this,
                    "Selecione um estádio."
            );
            return;
        }

        String codigo =
                jTableEstadios.getValueAt(linha, 1).toString();

        estadioController.excluir(codigo);

        carregarTabela();
        
        limparCampos();
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void txtAnoInauguracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoInauguracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoInauguracaoActionPerformed

    private void jTableEstadiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEstadiosMouseClicked
        System.out.println("Linha clicada");
        
        int linha = jTableEstadios.getSelectedRow();

        idEstadio.setText(
                jTableEstadios.getValueAt(linha,1).toString()
        );
        
        idEstadio.setEditable(false);

        nomeEstadio.setText(
                jTableEstadios.getValueAt(linha,0).toString()
        );

        txtLotacaoMax.setText(
                jTableEstadios.getValueAt(linha,2).toString()
        );

        txtAnoInauguracao.setText(
                jTableEstadios.getValueAt(linha,3).toString()
        );

        jcbSelecionarPais.setSelectedItem(
                jTableEstadios.getValueAt(linha,4).toString()
        );

        estadoPartida.setText(
                jTableEstadios.getValueAt(linha,5).toString()
        );

        cidadePartida.setText(
                jTableEstadios.getValueAt(linha,6).toString()
        );
    }//GEN-LAST:event_jTableEstadiosMouseClicked

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
        System.out.println("Botão Clicado");
        
        if(jTableEstadios.getSelectedRow() == -1){
                JOptionPane.showMessageDialog(
                        this,
                        "Selecione um estádio na tabela."
                );
                return;
            }
        
        try {
            
            String pais = (String) jcbSelecionarPais.getSelectedItem();

            if ("Todos".equals(pais)) {
                JOptionPane.showMessageDialog(
                        this,
                        "Selecione um país válido."
                );
                return;
            }

            estadioController.editar(
                    idEstadio.getText().trim(),
                    nomeEstadio.getText().trim(),
                    Integer.parseInt(txtLotacaoMax.getText()),
                    (String) jcbSelecionarPais.getSelectedItem(),
                    estadoPartida.getText().trim(),
                    cidadePartida.getText().trim(),
                    Integer.parseInt(txtAnoInauguracao.getText())
            );

            carregarTabela();

            limparCampos();

            JOptionPane.showMessageDialog(
                    this,
                    "Estádio atualizado com sucesso."
            );

        } catch(Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage()
            );
        }
    }//GEN-LAST:event_botaoEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
    
    public static void main(String args[]) {
        // 1. Setup the FlatLaf Light Look and Feel
            try {
            com.formdev.flatlaf.FlatLightLaf.setup();
            } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
            }
           
            Administrador adminTeste =
            new Administrador(
                    "Administrador Teste",
                    "admin@teste.com",
                    "123",
                    Usuario.Tipo.ADMINISTRADOR
            );

            SessaoUsuario.getInstancia()
                    .setUsuarioAtual(adminTeste);
            
            System.out.println(
                SessaoUsuario.getInstancia()
                        .getUsuarioAtual()
                        .getNomeCompleto()
                );

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaInicialEstadios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoNovo;
    private javax.swing.JButton botaoPesquisar;
    private javax.swing.JTextField cidadePartida;
    private javax.swing.JTextField estadoPartida;
    private javax.swing.JTextField idEstadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEstadios;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox<String> jcbSelecionarPais;
    private javax.swing.JPanel jpnlDadosEstadio;
    private javax.swing.JTextField nomeEstadio;
    private javax.swing.JTextField txtAnoInauguracao;
    private javax.swing.JTextField txtLotacaoMax;
    // End of variables declaration//GEN-END:variables
}
